Agoric/PlaygroundVat

package.json, test/test-node-version.js
Note that the package.json key "engines" doesn't enforce anything most of the time, which is why the test is added. 
[npm says](https://docs.npmjs.com/files/package.json#engines):
> "Unless the user has set the engine-strict config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency."
[Semver](https://www.npmjs.com/package/semver) is a relatively simple package that knows about versioning.
=> fixes issue #10. checks if node version >= current LTS (10.15.1)

package.json, test/test-vat.js
also dumps the source of the function, to illustrate the renaming problem
=> test-vat: switch to console.log, fails

src/host.js, src/main.js, src/vat/index.js, test/m1/m2.js, test/test-marshal.js, test/test-vat2.js
switch all remaining uses of explicit `log()` in tests to plain
`console.log()`, stop sending explicit `log` functions around
refs #5
=> remove remaining `log` objects

.eslintrc.js
This PR turns a few Airbnb recommendations off (or alters them) because we have widespread violations, many of which are intentional on our part. 
For `no-unused-vars`, I've set it such that we can have arguments to a function that are unused, but only if they have an underscore prefix. 
We should revisit these at a later date.
=> Change eslint settings to match our current practices 

.eslintrc.js, src/vat/webkey.js
This one's a doozy. :D 
We start out with the following errors:
We also have a lot of `def` undefined errors which are not shown for conciseness.
The different commits are probably the best ways to view the following:
1. Reorder the functions in the file such that we don't have 'used before defined' errors. Unfortunately, the diff doesn't show this correctly.
2. Fix undefined def and Nat, remove unused insist. 
3. Comment out unreachable code, remove Nat which is unused and an unused `rec`
4. Change the `for...of` to `every` or `forEach` depending on the use
None
`npm test`
`./node_modules/.bin/eslint --fix src/vat/webkey.js`
=> ESLint changes to src/vat/webkey.js

package-lock.json, package.json, src/host.js
1. Install bs58
2. Fix undefined def
We still have shadowing issues as well as an unused `buf`. I wasn't sure if this was purposeful or showing something else was missing. (Why would we create a `buf` but not use it?)
`npm test`
`./node_modules/.bin/eslint --fix src/host.js`
=> ESLint changes to src/host.js -- 4 unresolved errors

test/util.js
1. Change `for..of` to `forEach`
2. Use `Object.prototype.hasOwnProperty.call(` instead
3. Temporarily disable unreachable rule (otherwise get unnecessary return and unused arguments)
=> ESLint changes to test/util.js

test/test-pipeline.js
1. add global Vow
2. removed unused imports
3. change all to CamelCase
4. change argv to _argv if intentional but unused
5. change unnamed functions to arrow style
6. Remove two unused variables: `obj3` and `got`(We may need them, but I didn't see how. Brian, you may want to check this. )
7. Disable no-unused-vars for all of the intentionally named variables, like `got8`
=> eslint changes to test/test-pipeline.js

examples/contract/escrow.js, examples/contract/makeAlice.js, examples/contract/makeBob.js, examples/contract/makeContractHost.js, examples/contract/makeMint.js, examples/contract/simple_auction.js, examples/contractHost/alice/source/index.js, examples/contractHost/bob/source/index.js, examples/contractHost/escrow.js, examples/contractHost/host/source/index.js, examples/contractHost/mint/source/index.js, package.json, src/flow/flowcomm.js, src/host.js, src/main.js, src/vat/executionEngine.js, src/vat/index.js, src/vat/remotes.js, src/vat/scoreboard.js, src/vat/webkey.js, test/test-contract.js, test/test-endowments.js, test/test-marshal.js, test/test-nat.js, test/test-pipeline.js, test/test-remotes.js, test/test-vat.js, test/test-vat2.js
This changes the Vat code to use SES's new `s.makeRequire()` helper, so both host and guest code can use things like `Nat = require('@agoric/nat')` and `harden = require('@agoric/harden')`. When guest code with these imports is run outside of SES, they get the usual npm versions. When it runs inside SES, it gets corresponding in-realm objects, so we can write unit tests of the individual pieces without having to go through hoops.
refs #19
=> use require() instead of global Nat/def/harden

examples/contract/escrow.js
No template because the changes are small - fix intentionally unused arguments, and disable the errors around the `require` of `harden` that is written that way for use in SES.
=> ESLint changes to examples/contract/escrow.js

examples/contract/makeAlice.js, examples/contract/makeBob.js
makeAlice.js:
makeBob.js:
1. allow require of `@agoric/harden`
2. allow param reassign
3. fix intentionally unused args
4. allow `cancel` to go unused because it's important to note that it could be used.
=> ESLint changes to examples/contract/makeAlice.js and makeBob.js

examples/contractHost/alice/source/index.js, examples/contractHost/bob/source/index.js
Alice:
Bob:
1. Allow require of harden
2. Allow `mint` and `alice` to reference each other, same for `mint` and `bob`
3. fix intentionally unused args and vars
4. change unnamed function to arrow style
=> ESLint changes for examples/contractHost/alice and /bob 

examples/contractHost/escrow.js
1. allow import of harden
2. allow intentionally unused args
3. export escrowExchange as default
=> ESLint changes to examples/contractHost/escrow.js

examples/contract/simple_auction.js
Because simple_auction has parsing errors and seems to be in progress, I think we should not try to enforce the ESLint rules at this point. Thoughts?
=> ESLint changes to examples/contract/simple_auction.js

test/test-marshal.js
1. Remove unused imports
2. Consolidate multiple imports of `host`
3. Deal with undefined vars/arguments
4. Disable eslint on the intended `require` of `@agoric/harden`
We have a shadowing of `hash58`. Which do we want to use? We have one imported from `host` and one from `makeVatEndowments`.
=> ESLint changes to test/test-marshal.js

src/vat/index.js
1. Add SES as global
1. Combine flowcomm imports, but keep comments.
2. Comment out unused `msgre`. There is a later `msgre`, so I assume this might be switched to in the future. Could be wrong on this.
3. comment out the definition of marshal, since it is only used in commented out code. 
4. Remove unused buildSturdyRef - this is unused entirely. We could decide to keep this instead. 
5. comment out `arg` which is only used in commented out code
=> ESLint changes to src/vat/index.js

src/vat/notifyUponResolution.js
1. Mark `myVatID` as an unused arg with a `_` prefix
2. remove `nurCount` since unused
3. Rename `swissnum` that is a parameter of `notify` and which shadows the upper `swissnum` 
4. Change `for..of` to a `forEach`
5. Allow inner declarations [because we are using ES6](https://eslint.org/docs/rules/no-inner-declarations#when-not-to-use-it)
=> ESLint changes to src/vat/notifyUponResolution.js

src/vat/executionEngine.js
1. Allow the import of harden
2. Allow `marshal` to be used before define. `makeWebkeyMarshal` takes in `serializer` as a parameter, which uses `allocateSwissStuff` which references `marshal`, so there's not an easy reordering here.
3. Move `rxSendOnly` down to fix `doSendInternal` use before define
4. remove `resolutionOf` as a parameter, since it shadows an import. I believe this was a mistake, but I'm not 100% certain.
=> ESLint changes to src/vat/executionEngine.js

src/vat/scoreboard.js
1. Allow import of harden
2. remove unused imports
3. Assume that PR #60 will turn off the `for...of` errors
4. Allow intentionally unused vars, args
5. Comment out code that seems completely unused
=> ESLint changes to src/vat/scoreboard.js

examples/contract/simple_auction.js, src/flow/flowcomm.js, src/host.js, src/index.js, src/vat/webkey.js, test/m1/index.js, test/m1/m2.js, test/test-contract.js, test/test-endowments.js, test/test-marshal.js, test/test-nat.js, test/test-pipeline.js, test/test-sourcemap.js
This is a whole bunch of little changes, many of which are automatic due to --fix. The recent changes to Playground Vat added some things that weren't fixed by our first pass. 
This PR also includes fixes to a few remaining issues in files that have already gone through the review process:
1. We fix the parsing errors in simple_auction, because if ESLint can't parse it, it errors, even with `eslint-disable`
2. We allow unused vars and inconsistent returns in flowcomm.js.
3. Allow harden to be imported
4. Allow some unused vars, allow some shadowed vars
Does not include main.js, remotes.js or scoreboard.js since those files have ESLint changes that are still to be merged.
Once those other PRs are merged in, this PR makes it so that we have no ESLint errors.
=> ESLint changes -- small misc changes only
