Agoric/PlaygroundVat

examples/quorum/one/source/index.js
examples/quorum/threeA/source/index.js
examples/quorum/threeB/source/index.js
examples/quorum/threeC/source/index.js
examples/quorum/twoA/source/index.js
examples/quorum/twoB/source/index.js
examples/quorum/twoC/source/index.js

`./node_modules/.bin/eslint examples/quorum/**/*.js`

Eslint changes only for quorum example

---

examples/callResponse/left/source/index.js
examples/callResponse/right/source/index.js

remove unused vars from callResponse

---

test/test-nat.js

1. Add global Nat
2. Remove unused imports
3. Replace `funcToSource(s1)` with `s1code` (I assume this is what was intended)

ESLint changes to test/test-nat.js

---

test/test-notify.js

Add a underscore prefix to the unused argument

ESLint changes to test/test-notify.js

---

test/test-contract.js

Remove unused imports, change e to _e

ESLint Changes for test/test-contract.js

---

test/test-endowments.js

Just one change so I won't use the usual template - change the ++ to a +=1

ESLint fixes for test/test-endowments.js

---

test/test-flow.js

1. Change `++` to `+= 1`
2. Allow for intentionally unused vars

ESLint changes to test/test-flow.js

---

test/test-remotes.js

1. Remove harden
2. Fix intentional unused variables/arguments and intentional shadows of logConflict
3. Remove `remotes` as it seems to be unintentionally unused

ESLint changes for test/test-remotes.js

---

examples/contract/contractTest.js

No template because changes are simple: add _ prefix for intentional unused arguments

ESLint changes for examples/contract/contractTest.js

---

examples/contract/escrowExchange.js

1. Add global Q
2. Change unnamed functions to arrow functions

ESLint changes to examples/contract/escrowExchange.js

---

examples/contract/index.js

No template because only a few changes - remove unused imports and change to _argv

ESLint changes to examples/contract/index.js

---

examples/contract/makeContractHost.js

1. Allow require of `@agoric/harden`
2. Change unnamed functions to arrow style.
3. Change `++` to `+= 1`

ESLint changes to examples/contract/makeContractHost.js

---

examples/contract/makeMint.js

1. remove unused Flow
2. allow require of harden
3. Fix unused vars/args - some are used in commented out logs
4. Allow `mint` and `issuer` to be defined in terms of each other

ESLint changes to examples/contract/makeMint.js

---

examples/contractHost/driver/source/index.js

1. Allow intentionally unused args and vars

ESLint changes to examples/contractHost/driver/source/index.js

---

examples/counter.js

1. add global Flow and Vow
2. fix intentionally unused args
Where is `ext` coming from?

ESLint updates to examples/counter.js

---

examples/contractHost/host/source/index.js

1. allow import of harden
2. Change unnamed functions to arrow style
3. `++` to `+=1`
4. add` _` to `argv`

ESLint changes to examples/contractHost/host/source/index.js

---

examples/contractHost/mint/source/index.js

1. remove unused Flow
2. allow import of harden
3. allow _argv
4. allow issuer and mint to use each other
5. change unnamed function to arrow style

ESLint changes to examples/contractHost/mint/source/index.js

---

test/test-vat.js

1. add global Vow Flow
2. remove unused bundlecode
3. change unnamed functions to arrow style
4. allow intended unused args
5. various automatic spacing changes (due to --fix)

ESLint changes to test/test-vat.js

---

src/comms.js

1. Remove unnecessary imports
2. Use array destructuring to get `err`, `vals`
3. Allow intentionally unused args
4. Disable array-callback-return on `Pushstream.map`
5. Get an array of wantedHostIDs and map through them
I tried to test Fix 5 by running the callResponse example. Is there a better way to test this? I don't believe the tests actually touch the examples, is that right?

ESLint changes to src/comms.js

---

test/test-vat2.js

1. Add global Vow, Flow
2. Remove unused imports
2. Change all to CamelCase
3. Change unnamed functions to arrow style
4. allow intentional unused vars and args

ESLint changes to eslint-test-vat2

---

src/flow/flowcomm.js

1. disable eslint rule `no-use-before-define ` for this file. Vows, Flows, InnerVows, etc all reference each other. I was thinking we can revisit this when we split this file up. Thoughts?
2. allow import of harden
3. remove scheduleHack, which I couldn't find a use of anywhere in PlaygroundVat
4. change `++` and`--` to their longer equivalents
5. change function debugID to getDebugID so that the variable debugID can be defined
6. ESLint believes that the parameters of catch are not scoped to catch, so rename reason to reason2
7. for..of to forEach when iterating over arrays (map would be faster, but would also have an eslint error)
8. change unnamed functions to arrow style
9. allow intentionally unused args
10. Disable `class-methods-use-this` when the method intentionally does not use …

ESLint changes for src/flow/flowcomm.js

---

src/vat/remotes.js

1. Allow import of harden
2. Remove unused `fromVatID`
3. Allow `for...of` when not iterating over an Array
4. `doDecisionsAgree` (around line 183-184) is a little more tricky, but I believe this is equivalent. 
5. Move `makeRemoteForHostID` and `makeDecisionList`
6. `body.hasOwnProperty('op')` to `Object.prototype.hasOwnProperty.call(body, 'op')`

ESLint changes to src/vat/remotes.js

---

src/main.js

1. Turn off the for...of rule. Mark says for...of is now very performant and this is an outdated message.
1. Remove unused imports
2. Use const when possible - lines 50 and 51 I go back and forth on, since it's less elegant.
3. Switch to destructuring if possible. If not, disable. 
4. `for...of` to `forEach` when it seems easily doable
5. allow intentional unused args 
6. Switch to camelCase
7. Allow `getAddressesForHostID` as is. We may revisit it later, but for now, the logic is not easily expressed outside of a for...of

ESLint changes to src/main.js Also, turn off for...of rule

---

.travis.yml

Change TravisCI to run test script and lint-check script in parallel and fail if either fail

Change TravisCI to run test script and lint-check script in parallel

---

.eslintrc.js
package.json

Apply ESLint config in a standardized way across all repos, including the npm scripts related to linting

Standardized eslint

---

scripts/npm-audit-fix.sh

make sure AgoricBot is up to date before running npm audit fix, make sure branch doesn't already exist

Fix: make sure AgoricBot is up to date before running npm audit fix
